gcc -Wall -Werror -g -v search_2ndlvl.m -framework Foundation -framework QuartzCore -lobjc -o search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
