gcc -Wall -Werror -g -v search_root.m -framework Foundation -framework QuartzCore -lobjc -o search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
