gcc -Wall -Werror -g -v search_5thlvl.m -framework Foundation -framework QuartzCore -lobjc -o search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
