gcc -Wall -Werror -g -v search_3rdlvl.m -framework Foundation -framework QuartzCore -lobjc -o search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
