gcc -Wall -Werror -g -v tree_builder.m -framework Foundation -framework QuartzCore -lobjc -o tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
