xcrun -sdk macosx swiftc search_2ndlvl.swift
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
./search_2ndlvl
