xcrun -sdk macosx swiftc search_root.swift
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
./search_root
