xcrun -sdk macosx swiftc tree_builder.swift
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
./tree_builder
