xcrun -sdk macosx swiftc search_3rdlvl.swift
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
./search_3rdlvl
