gcc -Wall -Werror -g -v search_4thlvl.m -framework Foundation -framework QuartzCore -lobjc -o search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
