gcc -Wall -Werror -g -v search_1stlvl.m -framework Foundation -framework QuartzCore -lobjc -o search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
