xcrun -sdk macosx swiftc search_4thlvl.swift
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
./search_4thlvl
