xcrun -sdk macosx swiftc search_1stlvl.swift
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
./search_1stlvl
