xcrun -sdk macosx swiftc search_5thlvl.swift
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
./search_5thlvl
