import Foundation
import QuartzCore

var string1:String = "semquisprimiseleifendproinsuspendissetristiquehymenaeosluctusetlaciniarisusconubiamagnisetiampurusposuereclassauguenatoquepotentinequecurabiturelitinterdumsollicitudintacitiparturientnisldismollisfeugiatplacerataptentaliquetnamclassnisiclasscursusloremultricesrhoncustortorsednullanibhnatoquevelitsollicitudinauguepedeviverrafeugiatfusceorcimetusaliquamnullameuismodetiampellentesquecommodopretiumtemporfaucibusvestibulumvolutpattempusmaurispersapiensociiscurabiturportanullablanditerossollicitudinutrisuselementummiinceptoserosfeugiatdolornisitincidunttellusaliquetligulanecvolutpatullamcorpervivamusadipiscingcumaccumsanenimdictumpervelsuscipitlaoreetfeugiatcurabituretsenectuspretiumfermentumnisibibendumcumerosvestibulumsollicitudinlobortisvulputaterutrumnatoquemusmagnaquisviverramattisluctussedpenatibuserosarcuphaselluslectuscubiliatorquentinceptosscelerisqueridiculuspenatibusaeneanquisqueiaculisnecmassahabitasseodiojustonuncerosmagnaliberodolorultriciestemporsodalesperbibendumcuraefermentumdonecdictummontesposuerepellentesqueporttitorfelisaccurabitursemperidcuraefelisgravidavitaeeleifendvenenatissemperloremtorquenthabitassevehiculafamesclassaccumsanjustocubiliapenatibuscumposuerevehiculaduitortorerostempusinterdumtinciduntestfringillasodalespulvinarnislsenectusnetusidatmalesuadanasceturmattisduisvestibulumcurabiturbibenduminlitorainterdummalesuadasediaculisdonecmagnisnisiduiinsenectuseratorcipellentesquesociisconvallislaciniapurusfacilisisporttitoregetlitoramaurisnullaconubiatorquenthactristiquemolestienibhsemperelementumnullamurnaanullalobortistristiqueclassjustoconvallisegetvivamuscommodoconguemagnisconsequatmaurisdisvestibulumnatoquesodalespellentesqueenimdictumcondimentumsodalesvehiculahendreritutturpisnequenuncelitutpulvinarluctusfamesmusconvallisnetusdictumstelementumquamluctusclassvelitvehiculaacpurusmolestiefaucibustorquentrisuspharetraplaceratnequeeuismodlacusultriciesetquisconguevestibulumfusceaeneannamscelerisqueelementumnonconvallisplaceratcurabituregestaspulvinarhacfringilladuisauctorsednecvestibulumsitbibendumdisullamcorperfaucibusduisagittisnasceturmagnaduisportaduiconsequataeneannostraantenibhsenectusorcijustometusetullamcorpernecphasellusliberotellussemluctusconvallisnuncvelsuscipitturpiseratviverrapretiumnisinasceturegestasfeugiatmolestieviverrafaucibusvelitsapiennequeinnatoquemolestieinterdummaecenasaeneaninceptossociosquvenenatisetiaminceptosphasellusimperdietaliquametconsequatconvallistristiquecubilialobortisnequenullamidfacilisiliberoblanditaccumsanenimloremnullalacussuspendisseipsumintegerultriciesatinterdumpretiumpraesentlacusligulanequeametrisusvenenatisvulputaterhoncusdictumstsuscipitlacusquamviverraetaccumsansenectuseratrhoncuscursusdismalesuadavehiculamorbifaucibusloreminceptosporttitorsemperhabitantcrasblanditconsequatestsenectusinceptosultricesvivamusvitaeposuerecondimentumornarevitaemagnavolutpatplateapedeaptentcondimentumjustoplateajustopraesentrisusduisinceptosmaecenasrisussociislaciniavolutpatmolestiesednislestimperdietorcivulputatepretiumrisustorquentelithabitantelementumnonarcutacitiprimisnonbibendumsemluctuselementumlorembibendumsitblanditinceptosdiamprimisgravidainterdumquamparturientpellentesqueullamcorpermolestienatoquenonorcipenatibusfaucibusnequepurusquisquenasceturmalesuadaduiacettempusmusquamcumcubilianonummyliberolaoreeteucondimentumtempusconguehaccondimentumutpenatibustristiquemalesuadapretiumpotentidictumstipsumrhoncuscommododictumstfacilisilitoracrascommodonullajustomagnatellusrhoncusintegermollisultriciesodioinestpraesentvolutpattellusatporttitoradmagnamagnistortorenimmagnismonteslacuscumaccumsanconvallisaccumsanullamcorperornareiaculiselementumsuspendissemaecenasavelsemperegestaslacuslacinianascetursitdolorodioposuerevitaeposuerepraesentnonummysodalesvelpotentiestnetuspedebibenduminceptosaclectusinceptosquisfacilisismauristemporconsectetuerurnanostrapellentesqueportacubiliaplateafelispharetrafelisproinimperdietsapienatmattispraesentnostravelsempotentimollisconubiaorcinunctacitimagnisridiculuslobortisullamcorperfacilisiligulaparturientantelobortissuscipiteuismodplateafamesnullaegeteratportavitaemollismaecenasnonummyinviverratorquentutsedfacilisiametrhoncusmollisantenuncdolorpenatibusacsenectusmattisnontorquentdignissimrutrumvulputateegethymenaeosatcumaccumsanaliquetscelerisquenatoquenamnostranonlacusultricieslectustemporaeneansuscipiteuismodametlacusethabitassenasceturprimisaptentatutsedridiculusfeugiatmolestiemollispermontesrisuseuismodtorquentaeneanetinterdummusultriciesanullamfuscemagnistempusquammorbidonecfelisantequisquevehiculaphasellusportabibendumnonummyintegerdiamegestasloremeusollicitudinfacilisisfelisgravidaquislaciniaplaceraterosdictumstmagnahendreritproinnatoquefuscefringillaultricessodalesimperdietultricesrisusfeugiatpuruspretiumlacusaptentdictumstmolestiesuscipittacitiornareconubiasitturpisaptenteleifendanteutmalesuadadapibusfelismolestiemolestieinterdumcurabiturmaecenasprimisproineuismodcuraeornareintegerconvallisclassconsectetuersenectuspermorbifringilladuiaccumsanmontesnecnetusligulavenenatisvolutpatproinametpretiumsociosqudiamportaconsequatacconsectetuervestibulumenimultricesfaucibusconvallisfacilisiametcommodoaccumsanconvallisaccumsanaccumsanhabitassenetusdignissimtinciduntadipiscingphasellusimperdietporttitornibhpedehacdapibusmontesnibhhabitasseantetempuselitsempernatoquenibhlobortisdapibusinceptospharetrahabitantenimliberoscelerisquesociosquhabitassemagnaenimtemporfringillacursusultricieslacusphaselluspellentesquenonummydapibusprointinciduntsitegetproinantevariusetiamauctorquismalesuadadonecleopellentesquemolestienibhhendreritsuspendisserisusatinciduntluctustellusduiipsumetduipenatibusdignissimnasceturnecmagnainceptosimperdietvariusproinnisilobortisridiculusmaecenasatnostranequeperposueresuspendisseegestashymenaeosiaculisametmagnisquisdictumstsagittisfacilisiscursusleosapienduisvehiculamaurisauguepretiumpedemolestiesemurnaarcucommodoiaculistortorcrasconsectetuernondictumnasceturultricesvelatellusadipiscingvariusrisusvulputateultriciesfusceplateamusmontesaptentpenatibussitvivamusnibhcrasposuerefuscemagnalitorasemmusvolutpatvolutpatvolutpatfeugiatelementumprimisipsumpenatibusnibhnonridiculusvivamuscrassedsociosquarcucumhaclaoreetsitfelisfeugiatduiaptenttinciduntacblandit"

var string2:String = "forperfaucibusduisagittisnasceturmagnaduisportaduiconsequataeneannostraantenibhsenectusorcijustometusetullamcorpernecphasellusliberotellussemluctusconvallisnuncvelsuscipitturpiseratviverrapretiumnisinasceturegestasfeugiatmolestieviverrafaucibusvelitsapiennequeinnatoquemolestieinterdummaecenasaeneaninceptossociosquvenenatisetiaminceptosphasellusimperdietaliquametconsequatconvallistristiquecubilialobortisnequenullamidfacilisiliberoblanditaccumsanenimloremnullalacussuspendisseipsumintegerultriciesatinterdumpretiumpraesentlacusligulanequeametrisusvenenatisvulputaterhoncusdictumstsuscipitlacusquamviverraetaccumsansenectuseratrhoncuscursusdismalesuadavehiculamorbifaucibusloreminceptosporttitorsemperhabitantcrasblanditconsequatestsenectusinceptosultricesvivamusvitaeposuerecondimentumornarevitaemagnavolutpatplateapedeaptentcondimentumjustoplateajustopraesentrisusduisinceptosmaecenasrisussociislaciniavolutpatmolestiesednislestimperdietorcivulputatepretiumrisustorquentelithabitantelementumnonarcutacitiprimisnonbibendumsemluctuselementu"

var commonString:String = ""

var i:Int = 0
var j:Int = 0

var subsequenceArray:[[Int]] = [[Int]](repeating:[Int](repeating:0,count:(string2.characters.count + 1)),count:(string1.characters.count + 1))

let start: TimeInterval = CACurrentMediaTime()

for i in (0...(string1.characters.count - 1)).reversed(){
  for j in (0...(string2.characters.count - 1)).reversed(){
    if(string1[string1.index(string1.startIndex, offsetBy:i)] == string2[string2.index(string2.startIndex, offsetBy:j)]){
      subsequenceArray[i][j] = 1 + subsequenceArray[i+1][j+1]
    }
    else{
      if(subsequenceArray[i+1][j] > subsequenceArray[i][j+1]){
        subsequenceArray[i][j] = subsequenceArray[i+1][j]
      }
      else if (subsequenceArray[i+1][j] < subsequenceArray[i][j+1]){
        subsequenceArray[i][j] = subsequenceArray[i][j+1]
      }
    }
  }
}

i = 0
j = 0

while((i < string1.characters.count) && (j < string2.characters.count)){
  if(string1[string1.index(string1.startIndex, offsetBy:i)] == string2[string2.index(string2.startIndex, offsetBy:j)]){
    commonString = commonString + String(string1[string1.index(string1.startIndex, offsetBy:i)])
    i = i + 1
    j = j + 1
  }
  else if (subsequenceArray[i+1][j] >= subsequenceArray[i][j+1]){
    i = i + 1
  }
  else{
    j = j + 1
  }
}

print("\(CACurrentMediaTime() - start)")

//print("\(stringSample[stringSample.index(stringSample.startIndex,offsetBy:1)])")
