#import <Foundation/Foundation.h>
#import <QuartzCore/QuartzCore.h>

int main(){
  NSMutableString *commonString = [NSMutableString string];

  int i = 0, j = 0;
  int **subsequenceArray;

  NSString *string1 = @"semquisprimiseleifendproinsuspendissetristiquehymenaeosluctusetlaciniarisusconubiamagnisetiampurusposuereclassauguenatoquepotentinequecurabiturelitinterdumsollicitudintacitiparturientnisldismollisfeugiatplacerataptentaliquetnamclassnisiclasscursusloremultricesrhoncustortorsednullanibhnatoquevelitsollicitudinauguepedeviverrafeugiatfusceorcimetusaliquamnullameuismodetiampellentesquecommodopretiumtemporfaucibusvestibulumvolutpattempusmaurispersapiensociiscurabiturportanullablanditerossollicitudinutrisuselementummiinceptoserosfeugiatdolornisitincidunttellusaliquetligulanecvolutpatullamcorpervivamusadipiscingcumaccumsanenimdictumpervelsuscipitlaoreetfeugiatcurabituretsenectuspretiumfermentumnisibibendumcumerosvestibulumsollicitudinlobortisvulputaterutrumnatoquemusmagnaquisviverramattisluctussedpenatibuserosarcuphaselluslectuscubiliatorquentinceptosscelerisqueridiculuspenatibusaeneanquisqueiaculisnecmassahabitasseodiojustonuncerosmagnaliberodolorultriciestemporsodalesperbibendumcuraefermentumdonecdictummontesposuerepellentesqueporttitorfelisaccurabitursemperidcuraefelisgravidavitaeeleifendvenenatissemperloremtorquenthabitassevehiculafamesclassaccumsanjustocubiliapenatibuscumposuerevehiculaduitortorerostempusinterdumtinciduntestfringillasodalespulvinarnislsenectusnetusidatmalesuadanasceturmattisduisvestibulumcurabiturbibenduminlitorainterdummalesuadasediaculisdonecmagnisnisiduiinsenectuseratorcipellentesquesociisconvallislaciniapurusfacilisisporttitoregetlitoramaurisnullaconubiatorquenthactristiquemolestienibhsemperelementumnullamurnaanullalobortistristiqueclassjustoconvallisegetvivamuscommodoconguemagnisconsequatmaurisdisvestibulumnatoquesodalespellentesqueenimdictumcondimentumsodalesvehiculahendreritutturpisnequenuncelitutpulvinarluctusfamesmusconvallisnetusdictumstelementumquamluctusclassvelitvehiculaacpurusmolestiefaucibustorquentrisuspharetraplaceratnequeeuismodlacusultriciesetquisconguevestibulumfusceaeneannamscelerisqueelementumnonconvallisplaceratcurabituregestaspulvinarhacfringilladuisauctorsednecvestibulumsitbibendumdisullamcorperfaucibusduisagittisnasceturmagnaduisportaduiconsequataeneannostraantenibhsenectusorcijustometusetullamcorpernecphasellusliberotellussemluctusconvallisnuncvelsuscipitturpiseratviverrapretiumnisinasceturegestasfeugiatmolestieviverrafaucibusvelitsapiennequeinnatoquemolestieinterdummaecenasaeneaninceptossociosquvenenatisetiaminceptosphasellusimperdietaliquametconsequatconvallistristiquecubilialobortisnequenullamidfacilisiliberoblanditaccumsanenimloremnullalacussuspendisseipsumintegerultriciesatinterdumpretiumpraesentlacusligulanequeametrisusvenenatisvulputaterhoncusdictumstsuscipitlacusquamviverraetaccumsansenectuseratrhoncuscursusdismalesuadavehiculamorbifaucibusloreminceptosporttitorsemperhabitantcrasblanditconsequatestsenectusinceptosultricesvivamusvitaeposuerecondimentumornarevitaemagnavolutpatplateapedeaptentcondimentumjustoplateajustopraesentrisusduisinceptosmaecenasrisussociislaciniavolutpatmolestiesednislestimperdietorcivulputatepretiumrisustorquentelithabitantelementumnonarcutacitiprimisnonbibendumsemluctuselementumlorembibendumsitblanditinceptosdiamprimisgravidainterdumquamparturientpellentesqueullamcorpermolestienatoquenonorcipenatibusfaucibusnequepurusquisquenasceturmalesuadaduiacettempusmusquamcumcubilianonummyliberolaoreeteucondimentumtempusconguehaccondimentumutpenatibustristiquemalesuadapretiumpotentidictumstipsumrhoncuscommododictumstfacilisilitoracrascommodonullajustomagnatellusrhoncusintegermollisultriciesodioinestpraesentvolutpattellusatporttitoradmagnamagnistortorenimmagnismonteslacuscumaccumsanconvallisaccumsanullamcorperornareiaculiselementumsuspendissemaecenasavelsemperegestaslacuslacinianascetursitdolorodioposuerevitaeposuerepraesentnonummysodalesvelpotentiestnetuspedebibenduminceptosaclectusinceptosquisfacilisismauristemporconsectetuerurnanostrapellentesqueportacubiliaplateafelispharetrafelisproinimperdietsapienatmattispraesentnostravelsempotentimollisconubiaorcinunctacitimagnisridiculuslobortisullamcorperfacilisiligulaparturientantelobortissuscipiteuismodplateafamesnullaegeteratportavitaemollismaecenasnonummyinviverratorquentutsedfacilisiametrhoncusmollisantenuncdolorpenatibusacsenectusmattisnontorquentdignissimrutrumvulputateegethymenaeosatcumaccumsanaliquetscelerisquenatoquenamnostranonlacusultricieslectustemporaeneansuscipiteuismodametlacusethabitassenasceturprimisaptentatutsedridiculusfeugiatmolestiemollispermontesrisuseuismodtorquentaeneanetinterdummusultriciesanullamfuscemagnistempusquammorbidonecfelisantequisquevehiculaphasellusportabibendumnonummyintegerdiamegestasloremeusollicitudinfacilisisfelisgravidaquislaciniaplaceraterosdictumstmagnahendreritproinnatoquefuscefringillaultricessodalesimperdietultricesrisusfeugiatpuruspretiumlacusaptentdictumstmolestiesuscipittacitiornareconubiasitturpisaptenteleifendanteutmalesuadadapibusfelismolestiemolestieinterdumcurabiturmaecenasprimisproineuismodcuraeornareintegerconvallisclassconsectetuersenectuspermorbifringilladuiaccumsanmontesnecnetusligulavenenatisvolutpatproinametpretiumsociosqudiamportaconsequatacconsectetuervestibulumenimultricesfaucibusconvallisfacilisiametcommodoaccumsanconvallisaccumsanaccumsanhabitassenetusdignissimtinciduntadipiscingphasellusimperdietporttitornibhpedehacdapibusmontesnibhhabitasseantetempuselitsempernatoquenibhlobortisdapibusinceptospharetrahabitantenimliberoscelerisquesociosquhabitassemagnaenimtemporfringillacursusultricieslacusphaselluspellentesquenonummydapibusprointinciduntsitegetproinantevariusetiamauctorquismalesuadadonecleopellentesquemolestienibhhendreritsuspendisserisusatinciduntluctustellusduiipsumetduipenatibusdignissimnasceturnecmagnainceptosimperdietvariusproinnisilobortisridiculusmaecenasatnostranequeperposueresuspendisseegestashymenaeosiaculisametmagnisquisdictumstsagittisfacilisiscursusleosapienduisvehiculamaurisauguepretiumpedemolestiesemurnaarcucommodoiaculistortorcrasconsectetuernondictumnasceturultricesvelatellusadipiscingvariusrisusvulputateultriciesfusceplateamusmontesaptentpenatibussitvivamusnibhcrasposuerefuscemagnalitorasemmusvolutpatvolutpatvolutpatfeugiatelementumprimisipsumpenatibusnibhnonridiculusvivamuscrassedsociosquarcucumhaclaoreetsitfelisfeugiatduiaptenttinciduntacblandit";

  NSString *string2 = @"forperfaucibusduisagittisnasceturmagnaduisportaduiconsequataeneannostraantenibhsenectusorcijustometusetullamcorpernecphasellusliberotellussemluctusconvallisnuncvelsuscipitturpiseratviverrapretiumnisinasceturegestasfeugiatmolestieviverrafaucibusvelitsapiennequeinnatoquemolestieinterdummaecenasaeneaninceptossociosquvenenatisetiaminceptosphasellusimperdietaliquametconsequatconvallistristiquecubilialobortisnequenullamidfacilisiliberoblanditaccumsanenimloremnullalacussuspendisseipsumintegerultriciesatinterdumpretiumpraesentlacusligulanequeametrisusvenenatisvulputaterhoncusdictumstsuscipitlacusquamviverraetaccumsansenectuseratrhoncuscursusdismalesuadavehiculamorbifaucibusloreminceptosporttitorsemperhabitantcrasblanditconsequatestsenectusinceptosultricesvivamusvitaeposuerecondimentumornarevitaemagnavolutpatplateapedeaptentcondimentumjustoplateajustopraesentrisusduisinceptosmaecenasrisussociislaciniavolutpatmolestiesednislestimperdietorcivulputatepretiumrisustorquentelithabitantelementumnonarcutacitiprimisnonbibendumsemluctuselementu";

  if (string1 == nil || string2 == nil || string1.length == 0 || string2.length == 0){
    return 1;
  }

  subsequenceArray = (int **) malloc((string1.length + 1) * sizeof(int *));
  for(int i = 0; i <= string1.length; i++){
    subsequenceArray[i] = (int *)malloc((string2.length + 1) * sizeof(int));
  }

  for (i = 0; i <= string1.length; i++){
    for (j = 0; j <= string2.length; j++){
      subsequenceArray[i][j] = 0;
    }
  }

  CFTimeInterval start = CACurrentMediaTime();

  for (i = string1.length-1; i >= 0; i--){
    for (j = string2.length-1; j >= 0 ; j--){
      if([[NSString stringWithFormat:@"%c", [string1 characterAtIndex:i]] isEqual:[NSString stringWithFormat:@"%c", [string2 characterAtIndex:j]]]){
        subsequenceArray[i][j] = 1 + subsequenceArray[i+1][j+1];
      }
      else{
        if(subsequenceArray[i+1][j] > subsequenceArray[i][j+1]) subsequenceArray[i][j] = subsequenceArray[i+1][j];
        else if (subsequenceArray[i+1][j] < subsequenceArray[i][j+1]) subsequenceArray[i][j] = subsequenceArray[i][j+1];
      }
    }
  }

  i = 0;
  j = 0;

  while (i < string1.length && j < string2.length){
    if([[NSString stringWithFormat:@"%c", [string1 characterAtIndex:i]] isEqual:[NSString stringWithFormat:@"%c", [string2 characterAtIndex:j]]]){
      [commonString appendString:[NSString stringWithFormat:@"%c", [string1 characterAtIndex:i]]];
      i++;
      j++;
    }
    else if (subsequenceArray[i+1][j] >= subsequenceArray[i][j+1]) i++;
    else j++;
  }

  CFTimeInterval e_time = (CACurrentMediaTime() - start);

  printf("%lf\n", e_time);

  //NSLog(@"%@",commonString);
  //printf("%lu\n", commonString.length);
  return 0;
}
